-- Tracking serveur du funnel Système Viral.
-- Les tables sont privées (RLS sans policy publique) et accessibles uniquement
-- aux fonctions Netlify via la service role Supabase.

create table if not exists public.sv_registrations (
  id bigint generated by default as identity primary key,
  token text not null unique,
  email text,
  prenom text,
  telephone text,
  pays text,
  statut text not null default 'partial' check (statut in ('partial', 'registered', 'purchased', 'refunded')),
  visitor_id text,
  session_id text,
  landing_page text,
  referrer text,
  traffic_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  fbclid text,
  meta_fbc text,
  meta_fbp text,
  gclid text,
  ttclid text,
  mailerlite_synced_at timestamptz,
  first_optin_at timestamptz not null default now(),
  phone_added_at timestamptz,
  offer_started_at timestamptz not null default now(),
  offer_expires_at timestamptz not null default (now() + interval '7 days'),
  vsl_first_view_at timestamptz,
  vsl_started_at timestamptz,
  vsl_last_view_at timestamptz,
  vsl_max_seconds integer not null default 0,
  vsl_max_percent smallint not null default 0 check (vsl_max_percent between 0 and 100),
  vsl_completed_at timestamptz,
  offer_viewed_at timestamptz,
  offer_clicked_at timestamptz,
  checkout_clicked_at timestamptz,
  checkout_viewed_at timestamptz,
  purchased_at timestamptz,
  purchase_status text,
  purchase_currency text,
  purchase_gross_minor bigint not null default 0,
  purchase_refunded_minor bigint not null default 0,
  purchase_net_minor bigint not null default 0,
  purchase_promo_code text,
  last_event_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_sv_registrations_email
  on public.sv_registrations (lower(email)) where email is not null;
create index if not exists idx_sv_registrations_first_optin on public.sv_registrations (first_optin_at desc);
create index if not exists idx_sv_registrations_source on public.sv_registrations (traffic_source, utm_campaign);
create index if not exists idx_sv_registrations_purchase on public.sv_registrations (purchased_at desc) where purchased_at is not null;

create table if not exists public.sv_funnel_events (
  id bigint generated by default as identity primary key,
  token text references public.sv_registrations(token) on update cascade on delete set null,
  visitor_id text,
  session_id text,
  event_name text not null,
  event_value text,
  page_path text,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_sv_funnel_events_token_time on public.sv_funnel_events (token, occurred_at desc);
create index if not exists idx_sv_funnel_events_name_time on public.sv_funnel_events (event_name, occurred_at desc);
create index if not exists idx_sv_funnel_events_visitor on public.sv_funnel_events (visitor_id, occurred_at desc);
create unique index if not exists uq_sv_funnel_events_dedupe
  on public.sv_funnel_events (token, dedupe_key) where token is not null and dedupe_key is not null;

create table if not exists public.sv_video_progress (
  id bigint generated by default as identity primary key,
  token text not null references public.sv_registrations(token) on update cascade on delete cascade,
  video_id text not null default 'sv-freegift-vsl',
  session_id text,
  first_play_at timestamptz,
  last_signal_at timestamptz not null default now(),
  max_seconds integer not null default 0,
  max_percent smallint not null default 0 check (max_percent between 0 and 100),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (token, video_id)
);

create table if not exists public.sv_conversions (
  id bigint generated by default as identity primary key,
  external_order_id text not null unique,
  token text references public.sv_registrations(token) on update cascade on delete set null,
  email text,
  provider text not null default 'spiffy',
  status text not null,
  currency text not null default 'EUR',
  gross_minor bigint not null default 0,
  refunded_minor bigint not null default 0,
  net_minor bigint not null default 0,
  promo_code text,
  purchased_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_sv_conversions_token on public.sv_conversions (token);
create index if not exists idx_sv_conversions_email on public.sv_conversions (lower(email));
create index if not exists idx_sv_conversions_purchased on public.sv_conversions (purchased_at desc);

create or replace function public.set_sv_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_sv_registrations_updated_at on public.sv_registrations;
create trigger tr_sv_registrations_updated_at before update on public.sv_registrations
for each row execute function public.set_sv_updated_at();

drop trigger if exists tr_sv_video_progress_updated_at on public.sv_video_progress;
create trigger tr_sv_video_progress_updated_at before update on public.sv_video_progress
for each row execute function public.set_sv_updated_at();

drop trigger if exists tr_sv_conversions_updated_at on public.sv_conversions;
create trigger tr_sv_conversions_updated_at before update on public.sv_conversions
for each row execute function public.set_sv_updated_at();

alter table public.sv_registrations enable row level security;
alter table public.sv_funnel_events enable row level security;
alter table public.sv_video_progress enable row level security;
alter table public.sv_conversions enable row level security;

revoke all on public.sv_registrations from anon, authenticated;
revoke all on public.sv_funnel_events from anon, authenticated;
revoke all on public.sv_video_progress from anon, authenticated;
revoke all on public.sv_conversions from anon, authenticated;

comment on table public.sv_registrations is 'Source de vérité privée des opt-ins et conversions du funnel Système Viral.';
comment on table public.sv_funnel_events is 'Journal chronologique privé des événements du funnel Système Viral.';
comment on table public.sv_video_progress is 'Progression maximale de la VSL Système Viral par token.';
comment on table public.sv_conversions is 'Commandes et remboursements Système Viral rapprochés des opt-ins.';
